services:
  restart-db:
    container_name: restart-db
    image: mongo
    restart: always

  restart-rasa-duckling:
    container_name: restart-rasa-duckling
    image: rasa/duckling
    restart: always

  restart-rasa-actions:
    container_name: restart-rasa-actions
    image: restart-rasa-actions
    restart: always
    build:
      context: ./language/actions

  restart-rasa:
    container_name: restart-rasa
    image: restart-rasa
    depends_on:
      - restart-rasa-actions
      - restart-rasa-duckling
    restart: always
    build:
      context: ./language

  restart-system:
    container_name: restart-system
    image: restart-system
    ports:
      - "8082:8080"
    depends_on:
      - restart-db
      - restart-rasa
    restart: always
    build:
      context: .
      args:
        - MONGO_HOST=restart-db
        - RASA_HOST=restart-rasa
