services:
  restart-db: # Database service
    container_name: restart-db
    image: mongo
    networks:
      - restart-net
    ports:
      - "27017:27017"
    restart: unless-stopped

  restart-coco: # CoCo service
    depends_on:
      - restart-db
    container_name: restart-coco
    image: restart-coco
    networks:
      - restart-net
    ports:
      - "8080:8080"
    restart: unless-stopped
    build:
      context: .
      args:
        - MONGODB_HOST=restart-db
        - MONGODB_USERS_HOST=restart-db

networks:
  restart-net: