services:
  restart-db:
    container_name: restart-db
    image: mongo
    restart: always
    networks:
      - restart-net

  restart-duckling:
    container_name: restart-duckling
    image: rasa/duckling
    restart: always
    networks:
      - restart-net

  restart-transformer:
    container_name: restart-transformer
    image: pstlab/restart-transformer
    networks:
      - restart-net
    depends_on:
      - restart-duckling
    restart: always
    build:
      context: ./language

  restart:
    container_name: restart
    image: pstlab/restart
    ports:
      - "8080:8080"
    networks:
      - restart-net
    depends_on:
      - restart-db
      - restart-transformer
    restart: always
    build:
      context: .
      args:
        - MONGODB_HOST=restart-db
        - TRANSFORMER_HOST=restart-transformer
        - LOGGING_LEVEL=DEBUG
    environment:
      - MONGODB_HOST=restart-db
      - TRANSFORMER_HOST=restart-transformer

networks:
  restart-net: